
name = "nai-prompt-manager"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# [D1 Database Configuration]
# 请将下方的 id 替换为你真实的 D1 Database ID
[[d1_databases]]
binding = "DB"
database_name = "nai-db"
database_id = "f0223bc6-64ba-4a15-bc1b-5bdd128a0626"

[vars]
GUEST_PASSCODE = "nai_guest_123" # 默认游客口令，部署后请在后台修改或修改此处
